version: '3.8'

volumes:
  data:

services:
  postgres-compose:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "123456"
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data